name: Run Nimpkgs Crawler

on:
  workflow_call:
    inputs:
      flags:
        description: "flags for nimpkgs/crawler"
        type: string
        default: ""

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3

      - name: Build Crawler
        run: nix build "github:nimpkgs/crawler#aefc1a691e18fd08b29e5eb9abe2c9905a72ece2" --no-link

      - name: Run Crawler
        run: nix run "github:nimpkgs/crawler#aefc1a691e18fd08b29e5eb9abe2c9905a72ece2" -- ${{ inputs.flags }}

      - name: Commit Updates
        uses: daylin-bot/actions/commit-and-push@main
        with:
          message: "update nimpkgs"
